### ISSUE TITLE
Overview - 4 points

### ISSUE THREAD

**Issue by MBVeilis** [michael2750/Flask_on_NGINX#1]
Problemstilling ikke tydeliggjort nok i indledning/problemformulering. Hvilke problemer løser NGINX og Flask?  

Det ville være fordelagtigt at bruge sammenligninger med alternativer for Flask/NGINX.

**Comment by michael2750** [comment]
Vi har udvidet vores blog ved at sammenligne NGINX, med HAProxy som også er et større system der konkurrere side om side.
