### ISSUE TITLE
Previous Work/ Future Work - 4 point

### ISSUE THREAD

**Issue by MBVeilis** [michael2750/Flask_on_NGINX#6]
“Ved at implementere NGINX i sin applikation, vil det være en økonomisk besparelse i forhold til, hvis man ellers skulle ud og opgradere sit hardware, som alligevel på et tidspunkt ikke ville være tilstrækkeligt.” God overvejelse mht. fremtidige projekter. 

Kunne dog godt være flere fremtidige overvejelser, hvad angår nye projekter. 
F.eks: 
Ville i blive ved med at bruge Flask/NGINX? Eller ville i anbefale andre teknologier?”

**Comment by michael2750** [comment]
Vi har skrevet en lille sektion under “Konklusion” om hvorvidt vi vil bruge NGINX i fremtidige applikationer.
